### ISSUE TITLE
Command line tools don't work on Windows

### ISSUE THREAD

**Issue by omad** [conda-forge/datacube-feedstock#14]
## Issue

Installing datacube conda packages from this feedstock don't install working executable `datacube` command line tools in Windows.

## Reproduce
`conda create -c conda-forge --name cubeenv python=3.6 datacube=1.6.2`

Executables are created in the `%CURRENT_ENV%\Scripts` named `datacube`, but they are text files which look like:
<details>

```python
#!/bin/sh
'''exec' C:/Users/u68320/AppData/Local/Continuum/miniconda3/envs/cubeenv/bin/python "$0" "$@"
' '''
# -*- coding: utf-8 -*-
import re
import sys

from datacube.scripts.cli_app import cli

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(cli())
```

</details>

## Potential Fix
They should be windows executables with names like `datacube.exe`.

I suspect that switching away from being a `noarch` build will fix this.

**Comment by Kirill888** [comment]
Fixed by #17
