### ISSUE TITLE
Update maintainer list

### ISSUE THREAD

**Issue by Kirill888** [conda-forge/datacube-feedstock#39]
### Comment:

1. Need to add @SpacemanPaul as he is most active in `datacube-core` currently
2. Possibly prune out no longer active maintainers

https://github.com/conda-forge/datacube-feedstock/blob/6bb842c5e7006d949afdc7382e7438e190ca157d/recipe/meta.yaml#L94-L100

**Comment by SpacemanPaul** [comment]
GypsyBojangles can definitely go.  Andrew is questionable.
